version: '2'
services:
  web:
    build: frontend
    volumes:
      - ./frontend/web:/usr/local/apache2/htdocs/

  haproxy:
    build: haproxy
    ports:
     - "80:80"
    volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
     - mongo
     - logstash
     - web

  logstash:
    build: logstash
    volumes:
    - ./logstash/logstash-input.conf:/etc/logstash/logstash.conf:ro
    ports:
     - "2000:2000"
    links:
     - rabbitmq

  logstash-mongo:
    build: logstash
    volumes:
    - ./logstash/logstash-output.conf:/etc/logstash/logstash.conf:ro
    links:
     - mongo
     - rabbitmq


  mongo:
    image: mongo
    command: mongod --rest --httpinterface
    ports: 
     - "27017:27017"
     - "28017:28017"

  rabbitmq:
    image: rabbitmq
    hostname: "rabbitmq"
    ports:
     - "5672:5672"
